version: 2
updates:
  # GitHub Actions のみをDependabotで管理
  # pnpm依存関係はRenovateが担当
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"