name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on size
        uses: codelytv/pr-size-labeler@4ec67706cd878fbc1c8db0a5dcd28b6bb412e85a # v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: 10
          s_label: 'size/S'
          s_max_size: 100
          m_label: 'size/M'
          m_max_size: 500
          l_label: 'size/L'
          l_max_size: 1000
          xl_label: 'size/XL'
          fail_if_xl: false  # XLサイズでも失敗させない
          message_if_xl: |
            このPRは非常に大きいです（1000行以上の変更）。
            レビューを容易にするため、可能であれば分割を検討してください。
          files_to_ignore: |
            pnpm-lock.yaml
            package-lock.json
            yarn.lock
            *.generated.*
            *.min.js
            *.min.css