name: Renovate Validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate-validation.yml'

jobs:
  validate:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator